import type { Row } from "../taxonomy";

/* Real, named programs and well-known activity types. Details change, so the site tells
   students to confirm dates and eligibility with each organizer. */
export const CURATED: Row[] = [
  // Math and computing competitions
  "USA Computing Olympiad (USACO)|comp|stem|cs,ds,math|code,math,comp|c,m|M|o|Free online algorithm contests with Bronze, Silver, Gold, and Platinum divisions.|Start at Bronze. Past problems and solutions are free on the USACO site.",
  "American Mathematics Competitions (AMC 10/12)|comp|stem|math,cs,chem,eng,ds|math,comp|m|L|p|75-minute problem-solving exams that qualify top scorers for AIME and the USA Math Olympiad.|Ask your math department if your school registers; past tests are on the AoPS wiki.",
  "Harvard-MIT Mathematics Tournament (HMMT)|comp|stem|math,cs|math,comp,team|m|L|p|Student-run team and individual math tournament held at Harvard and MIT.|Form a team of strong problem solvers early in the fall.",
  "Princeton University Mathematics Competition (PUMaC)|comp|stem|math,cs|math,comp,team|m|L|p|Student-run math tournament with individual, team, and power rounds.|Practice with past PUMaC power rounds; they reward proof writing.",
  "American Regions Mathematics League (ARML)|comp|stem|math,cs|math,comp,team|m|L|p|Team math competition where regional teams compete at multiple sites each spring.|Most teams are formed by regional math leagues; ask your coach.",
  "Math Prize for Girls|comp|stem|math,cs,eng|math,comp|m|L|p|Individual math competition for girls held at MIT.|Qualification uses AMC scores, so take the AMC first.",
  "Purple Comet! Math Meet|comp|stem|math,cs|math,comp,team|m|L|o|Free online international team math competition.|Great first team contest for a new math club.",
  "Math Kangaroo|comp|stem|math|math,comp|m|L|p|International math competition with levels up through 12th grade.|Good low-pressure entry point for younger students.",
  "Mu Alpha Theta|club|stem|math,edu|math,comp,lead|m|M|p|National math honor society with chapter competitions and tutoring.|If your school has no chapter, a math teacher can sponsor one.",
  "Codeforces Contests|comp|stem|cs,math,ds|code,math,comp|c,m|M|o|Frequent online programming contests with a public rating.|Join Div. 3 or Div. 4 rounds first and upsolve after each contest.",
  "Advent of Code|proj|stem|cs,ds|code,math|c|L|o|Daily programming puzzles each December, solvable in any language.|Share solutions on GitHub to build a public portfolio.",
  "Kaggle Competitions|comp|stem|ds,cs,math|code,math,res|c,m|M|o|Data science and machine learning competitions on real datasets.|Start with the Getting Started competitions and read top public notebooks.",
  "Congressional App Challenge|comp|stem|cs,eng|code,create|c|M|o|Students submit an original app to their U.S. House district's competition.|Check that your representative participates before you start.",
  "picoCTF|comp|stem|cs,eng|code,math,comp|c|L|o|Free beginner-friendly cybersecurity capture-the-flag competition from Carnegie Mellon.|The practice gym stays open year-round.",
  "CyberPatriot|comp|stem|cs,eng|code,team,comp|c|M|p|National youth cyber defense competition run by the Air & Space Forces Association.|Teams need an adult coach; a CS teacher is a good ask.",
  "Technovation Girls|comp|stem|cs,bus,eng|code,create,team|c,bu|M|o|Teams of girls build a mobile app or AI project that solves a community problem.|Find a mentor through the program's matching system.",
  "NCWIT Award for Aspirations in Computing|comp|stem|cs,ds|code,lead|c|L|o|Recognition for high school students who identify as women, genderqueer, or nonbinary and are active in computing.|Document projects and outreach before you apply.",
  "Girls Who Code Club|club|stem|cs,ds|code,team,lead|c|L|b|Free after-school coding clubs with a ready-made curriculum.|Any adult facilitator can start a club at your school or library.",
  "Kode With Klossy|summer|stem|cs,ds|code,create|c|H|o|Free summer coding camps for young women and gender-expansive youth.|Apply early; spots are limited.",
  // Science competitions
  "Science Olympiad|comp|stem|bio,chem,eng,env,cs|res,team,comp,build|b,ch,p,es|M|p|Team competition across 23 events from anatomy to engineering builds.|Pick events that match your intended major.",
  "Regeneron International Science and Engineering Fair (ISEF)|comp|stem|bio,chem,eng,env,cs,psy|res,write,speak|b,ch,p,es,c|H|p|The largest international pre-college science fair, reached through affiliated regional fairs.|Find your ISEF-affiliated regional fair first; its rules decide your timeline.",
  "Regeneron Science Talent Search|comp|stem|bio,chem,eng,math,cs,psy|res,write|b,ch,p,m|H|o|Research competition for high school seniors with a detailed written application.|Plan your research during junior year.",
  "Junior Science and Humanities Symposium (JSHS)|comp|stem|bio,chem,eng,env,psy|res,speak,write|b,ch,p,es|H|p|Students present original research at regional and national symposia.|Regional symposia accept papers on a fall and winter schedule.",
  "USA Physics Olympiad (F=ma)|comp|stem|chem,eng,math|math,res,comp|p,m|L|p|The F=ma exam is the first round of selection for the U.S. Physics Team.|Work through past F=ma exams under timed conditions.",
  "U.S. National Chemistry Olympiad (USNCO)|comp|stem|chem,bio,nur|res,math,comp|ch|L|p|Local section exams lead to the national exam and the U.S. team camp.|Contact your local ACS section about the local exam.",
  "USA Biology Olympiad (USABO)|comp|stem|bio,nur,psy|res,comp|b|L|p|Open exam leads to semifinals and a national finals camp.|Campbell Biology is the standard prep text.",
  "USA Earth Science Olympiad (USESO)|comp|stem|env,chem|res,comp|es|L|o|Earth science exam that selects the U.S. team for the International Earth Science Olympiad.|Review geology, meteorology, oceanography, and astronomy.",
  "USA Astronomy and Astrophysics Olympiad (USAAAO)|comp|stem|chem,math,eng|math,res,comp|p,m|L|o|Exams that select the U.S. team for the international astronomy olympiad.|Brush up on physics and basic astronomy math.",
  "National Science Bowl|comp|stem|chem,bio,env,eng,math|comp,team|b,ch,p,m,es|M|p|Department of Energy quiz competition across math and science.|Practice with the official question sets on the DOE site.",
  "National Ocean Sciences Bowl (NOSB)|comp|env|env,bio|comp,team,res|b,es|M|p|Quiz bowl and research presentation competition on ocean science.|Coastal and inland regions both host bowls.",
  "USA Brain Bee|comp|health|bio,psy,nur|res,comp|b,ps|L|b|Neuroscience competition that leads to the International Brain Bee.|Start with the official study materials.",
  "Genes in Space|comp|stem|bio,eng|res,create|b|M|o|Students propose DNA experiments that could run on the International Space Station.|Read past winning proposals before writing yours.",
  "Stockholm Junior Water Prize (U.S.)|comp|env|env,eng,bio,chem|res,write|es,ch,b|H|p|Water-focused science research competition with state and national rounds.|Projects can be lab or field research.",
  "Conrad Challenge|comp|stem|eng,bus,env,bio|create,team,lead|bu,p,b|M|o|Innovation and entrepreneurship competition for teams solving global problems.|Pick a narrow, concrete problem you can prototype.",
  "Toshiba/NSTA ExploraVision|comp|stem|eng,bio,env|create,team,res|b,p,es|M|o|K-12 teams imagine a technology 20 years in the future.|Needs a teacher sponsor; teams of two to four.",
  "Breakthrough Junior Challenge|comp|stem|bio,chem,math,cs|create,speak|b,ch,p,m|M|o|Make a short video explaining a big idea in physics, life science, or math.|Show your script to someone outside science before filming.",
  "MIT THINK Scholars Program|comp|stem|eng,cs,chem,bio|res,write,create|p,c,b|M|o|Research proposal competition that funds and mentors winning projects.|Proposals are judged on feasibility, so keep scope tight.",
  "Davidson Fellows Scholarship|comp|stem|math,cs,bio,wri,mus,phil|res,create|m,b,e,mu|H|o|Scholarship for students 18 and under with a significant completed project.|Best for students who already have deep independent work.",
  "Lemelson-MIT InvenTeams|comp|stem|eng,cs|build,team,create|p,c|H|p|Grants for high school teams to invent a technological solution to a real-world problem.|Requires an educator to apply on behalf of the team.",
  // Engineering and making
  "FIRST Robotics Competition (FRC)|club|stem|eng,cs,bus|build,team,code,comp|p,c|H|p|Teams design, build, and program industrial-size robots in six weeks.|Non-technical roles like outreach and business count too.",
  "FIRST Tech Challenge (FTC)|club|stem|eng,cs|build,team,code,comp|p,c|H|p|Smaller robot competition with a big engineering notebook component.|Keep a detailed engineering notebook; judges weigh it heavily.",
  "VEX Robotics Competition|club|stem|eng,cs|build,team,code,comp|p,c|H|p|Robotics competition with yearly game challenges and many local tournaments.|Local events are frequent, so you can compete often.",
  "MATE ROV Competition|comp|stem|eng,env|build,team|p,es|H|p|Teams build underwater remotely operated vehicles for ocean-themed missions.|Regional events run in spring.",
  "American Rocketry Challenge|comp|stem|eng,chem|build,team,math|p,m|M|p|Teams design and fly model rockets to hit altitude and time targets.|Read the safety code first; the rules are strict.",
  "Technology Student Association (TSA)|club|stem|eng,cs,arch,art|build,create,comp|p,c,a|M|p|Career and technical student organization with dozens of STEM competitive events.|Pick one build event and one presentation event.",
  "TEAMS Engineering Competition|comp|stem|eng|team,math,comp|p,m|L|p|TSA's team engineering challenge with tests and design tasks.|Mix students strong in math and in building.",
  "SkillsUSA|club|stem|eng,arch,bus|build,lead,comp|p,bu|M|p|Career and technical organization with contests in trades, technology, and leadership.|Great fit if you take career-tech classes.",
  "Maker Space / Engineering Club|club|stem|eng,art,arch|build,create|p,a|L|p|Build gadgets, 3D print, and prototype ideas.|Document builds with photos for applications.",
  // STEM summer programs
  "Research Science Institute (RSI)|summer|stem|bio,chem,math,cs,eng|res,write,speak|m,b,ch,p|H|p|Free six-week summer research program at MIT for rising seniors.|Highly selective; strong math or science competition history helps.",
  "PROMYS|summer|stem|math|math,res|m|H|p|Six-week summer program at Boston University focused on number theory.|The application problem set is the most important part.",
  "Ross Mathematics Program|summer|stem|math|math,res|m|H|p|Intensive summer number theory program built around proofs.|Application problems reward careful written reasoning.",
  "Canada/USA Mathcamp|summer|stem|math,cs|math,res|m|H|p|Five-week summer program for mathematically talented students.|The qualifying quiz is hard by design; partial progress counts.",
  "Hampshire College Summer Studies in Mathematics (HCSSiM)|summer|stem|math|math,res|m|H|p|Six-week summer math program focused on proofs and discovery.|Show curiosity in your application, not just results.",
  "Summer Science Program (SSP)|summer|stem|chem,bio,math|res,team,math|p,ch,b|H|p|Teams do real research in astrophysics, biochemistry, or genomics.|Financial aid is need-based and generous.",
  "MIT Beaver Works Summer Institute|summer|stem|eng,cs|build,code,team|p,c|H|b|Rigorous summer engineering courses in areas like autonomous vehicles.|Most courses have an online prerequisite course in spring.",
  "Stanford Institutes of Medicine Summer Research Program (SIMR)|summer|health|bio,nur,eng|res|b,ch|H|p|Eight-week summer biomedical research internship at Stanford.|Open to students in specific grades and regions; check eligibility.",
  "Garcia Summer Research Program|summer|stem|chem,eng,bio|res|ch,p|H|p|Polymer and materials science research at Stony Brook University.|Projects often lead to science fair submissions.",
  "Simons Summer Research Program|summer|stem|bio,chem,math,cs|res|b,ch,p,m|H|p|Research with Stony Brook faculty for rising seniors.|Requires U.S. citizenship or permanent residency.",
  "Clark Scholars Program|summer|stem|bio,chem,eng,math,cs|res|b,ch,p,m|H|p|Seven-week research program at Texas Tech University with a stipend.|Applicants must be at least 17 by the start date.",
  "COSMOS (California State Summer School for Mathematics and Science)|summer|stem|bio,chem,eng,math,cs|res,team|b,ch,p,m|H|p|Month-long residential STEM program at several University of California campuses.|Pick a cluster that matches your intended major.",
  "Boston University RISE|summer|stem|bio,chem,eng,psy,cs|res|b,ch,p|H|p|Six-week summer research internship or practicum for rising seniors.|Choose between the internship and the practicum track carefully.",
  "Jackson Laboratory Summer Student Program|summer|health|bio,nur|res|b|H|p|Ten-week genetics and genomics research program with a stipend.|Open to students who will be at least 18 or college students; check current rules.",
  "NASA OSTEM High School Internships|work|stem|eng,cs,bio,chem|res,build,code|p,c|H|b|Paid internships at NASA centers for U.S. citizens 16 and older.|Apply through the NASA STEM Gateway early.",
  "State Governor's School|summer|stem|und,math,bio,wri,art|res,create|m,b,e|H|p|Many states run free selective summer programs for high school students.|Search your state's program name and nomination process.",
  "Carnegie Mellon Pre-College Programs|summer|stem|cs,eng,art,arch,mus|code,create|c,a|H|p|Summer programs in computing, art, architecture, drama, and music.|Some programs offer need-based aid.",
  // Research mentorship
  "Polygence Research Mentorship|res|stem|und,bio,cs,psy,hist,wri|res,write|b,c,ps,h|M|o|Paid program pairing students with a mentor to complete a research project.|Finish with a paper or product you can show; scholarships exist.",
  "Pioneer Academics|res|stem|und,bio,bus,psy,hist,phil|res,write|b,ec,ps,h|M|o|Paid online research program where students write a college-level paper with a professor.|Ask about need-based scholarships.",
  "Lumiere Research Scholar Program|res|stem|und,bio,cs,bus,psy|res,write|b,c,ec,ps|M|o|Paid one-on-one research mentorship with university researchers.|Pick a question small enough to finish in a semester.",
  "Cold-Email a Professor for Research|res|stem|bio,chem,psy,cs,eng,env|res,write|b,ch,p,c,ps|H|p|Ask a local university lab if you can assist with a project.|Read one of their papers first and ask a specific, short question.",
  // Health
  "HOSA - Future Health Professionals|club|health|bio,nur,psy|comp,speak,lead|b,he|M|p|Health-science competitions and leadership for future healthcare workers.|Start a chapter if your school doesn't have one.",
  "Hospital Volunteer Program|vol|health|bio,nur,psy|help,team|b,he|M|p|Volunteer in a hospital setting with patients and staff.|Many hospitals require a minimum age and a TB test; apply early.",
  "Red Cross Club|club|health|bio,nur,und|help,org,lead|he|L|p|School club that runs blood drives, disaster preparedness, and first aid trainings.|Running a blood drive gives you measurable impact.",
  "Organize a Blood Drive|lead|health|bio,nur,bus|org,lead,help|he|L|p|Work with a blood collection organization to host a drive at school.|Track units collected; it makes the impact concrete.",
  "CPR and First Aid Certification|course|health|nur,bio,kin|help|he|L|p|Get certified in CPR, AED, and first aid.|Certification is a prerequisite for many volunteer and job roles.",
  "Certified Nursing Assistant (CNA) Training|course|health|nur,bio|help,team|b,he|H|p|State-approved training to work as a nursing assistant.|Age minimums vary by state; some high schools offer it.",
  "EMT Certification|course|health|nur,bio,kin|help,team|b,he|H|p|Emergency medical technician training; some states allow students under 18.|Check your state's age rules before enrolling.",
  "Medical Exploring Post|club|health|bio,nur|team,help|b,he|M|p|Career exploration groups hosted by hospitals through Learning for Life Exploring.|Search for posts hosted by local hospitals or EMS agencies.",
  "Stanford Medical Youth Science Program (SMYSP)|summer|health|bio,nur|res,help|b,he|H|p|Free summer program for low-income students interested in medicine.|Eligibility is limited to certain Northern California areas.",
  "NAMI on Campus High School Club|club|health|psy,nur|help,lead,speak|ps,he|L|p|Student mental health awareness club supported by NAMI.|Pair awareness events with a concrete resource list.",
  "Peer Counseling Program|vol|health|psy,edu|help|ps|M|p|Train in peer support and active listening at school.|Many schools train students in a spring cohort.",
  "Best Buddies|club|svc|edu,psy,nur|help,team|ps|L|p|Build friendships with students with intellectual and developmental disabilities.|Consistency matters more than event count.",
  "Special Olympics Unified Sports|vol|ath|kin,edu,psy|help,team|he,ps|M|p|Play on teams that combine athletes with and without intellectual disabilities.|Ask your athletic director if your school has a Unified team.",
  // Business
  "DECA|club|biz|bus,law|speak,comp,lead|bu,ec|M|p|Business case competitions, roleplays, and presentations.|Roleplay events reward confident speaking.",
  "FBLA (Future Business Leaders of America)|club|biz|bus,cs|speak,comp,lead|bu,ec|M|p|Business competitions, tests, and leadership conferences.|Test events are a low-stress way to start.",
  "Business Professionals of America (BPA)|club|biz|bus,cs|comp,org|bu,c|M|p|Career organization with business, finance, and IT competitions.|Pick events tied to classes you're already taking.",
  "Junior Achievement Company Program|proj|biz|bus|lead,team,create|bu,ec|M|p|Students run a real small company from idea to liquidation.|Volunteer for a finance or sales role to get numbers you can cite.",
  "Diamond Challenge|comp|biz|bus,eng|create,team,speak|bu|M|o|High school entrepreneurship competition from the University of Delaware.|Social innovation and business concept tracks are both open.",
  "Wharton Global High School Investment Competition|comp|biz|bus,math,ds|math,team,res|ec,bu,m|M|o|Teams manage a virtual portfolio and present a strategy.|Write down why you made every trade; the presentation needs it.",
  "National Economics Challenge|comp|biz|bus,math|math,res,comp|ec|L|b|Economics competition for high school teams.|Teams of three or four work best.",
  "High School Fed Challenge|comp|biz|bus,law|res,speak,team|ec,g|M|p|Teams analyze the economy and give a monetary policy recommendation.|Offered by several Federal Reserve districts; check yours.",
  "LaunchX Entrepreneurship Program|summer|biz|bus,eng,cs|create,lead,team|bu|H|b|Summer program where teams start real companies.|Have a rough idea of problems you care about before applying.",
  "Blue Ocean Entrepreneurship Competition|comp|biz|bus|create,speak|bu|M|o|Students pitch an original business idea.|Focus your pitch on a specific customer.",
  "NFTE World Series of Innovation|comp|biz|bus|create,team|bu|L|o|Young people propose innovative solutions to global challenges.|Short format; good first pitch competition.",
  "The Stock Market Game|comp|biz|bus,math|math,res|ec,m|L|o|Teams manage a simulated $100,000 portfolio.|Ask your economics teacher to register a class.",
  "Investment Club|club|biz|bus,math,ds|math,res,team|ec,m|L|p|Study companies and run a mock portfolio.|Publish a monthly stock pitch to practice writing.",
  "FCCLA (Family, Career and Community Leaders of America)|club|biz|edu,bus,nur|lead,create,help|bu,he|M|p|Career organization covering leadership, culinary, fashion, and community service.|Competitive events reward community service projects.",
  "Start a Small Business|proj|biz|bus,art|lead,create,org|bu|H|p|Sell a product or service and track real revenue.|Numbers like customers and revenue make it concrete.",
  "Part-Time Job|work|biz|und,bus|org,team|bu|M|p|Work a job; colleges value responsibility.|Jobs count as activities; describe what you learned.",
  // Civics and debate
  "Speech and Debate (NSDA)|club|civ|law,wri,bus,phil|speak,res,comp|g,e,h|H|p|Compete in policy, Lincoln-Douglas, public forum, or speech events.|Public Forum is the most beginner-friendly.",
  "Model United Nations|club|civ|ir,law,bus|speak,team,lead|g,h|M|p|Represent countries and negotiate resolutions.|Chairing a committee shows leadership.",
  "Mock Trial|club|civ|law,wri|speak,team,comp|g,e|M|p|Play attorneys and witnesses in simulated trials.|Witness roles are great for theater students too.",
  "Student Government|lead|civ|law,bus,edu|lead,org,speak|g|M|p|Represent your class and run school initiatives.|Highlight one concrete thing you changed.",
  "Local Campaign Volunteer|vol|civ|law|org,team,write|g|M|p|Work for a campaign, council member, or advocacy group.|Local offices often welcome high school volunteers.",
  "YMCA Youth and Government|club|civ|law|speak,lead,write|g|M|p|Students write bills and run a model state government.|Bill writing is a strong writing sample.",
  "Boys State and Girls State|summer|civ|law,ir|lead,speak|g|M|p|American Legion week-long programs where juniors build a mock state government.|Usually nominated by your school in junior year.",
  "United States Senate Page Program|work|civ|law|org|g|H|p|High school juniors serve as pages in the U.S. Senate.|Appointment goes through a senator's office.",
  "Junior State of America (JSA)|club|civ|law,ir|speak,lead|g|M|p|Student-run debate and political awareness organization.|Conventions are open to all members.",
  "We the People|comp|civ|law,hist|speak,res,team|g,h|M|p|Class-based competition with simulated congressional hearings on the Constitution.|Usually run through a government class.",
  "Model Congress|club|civ|law|speak,write|g|M|p|Simulate the U.S. Congress at college-hosted conferences.|Bring a well-researched bill.",
  "Poll Worker|vol|civ|law|org,help|g|L|p|Many states let 16- and 17-year-olds work at polling places, often paid.|Check your county election office for student programs.",
  "Mayor's Youth Council|lead|civ|law,edu|lead,speak,org|g|M|p|Advise local government on issues affecting young people.|Search your city's website for youth commission openings.",
  "Profile in Courage Essay Contest|comp|civ|law,hist,wri|write,res|h,g,e|L|o|JFK Library essay contest about political courage.|Pick a lesser-known official; it reads as more original.",
  "National High School Ethics Bowl|comp|hum|phil,law|speak,team,res|g,e|M|p|Teams discuss real ethical cases in a collaborative format.|Prepare cases with people who disagree with you.",
  // Humanities
  "National History Day|comp|hum|hist,wri,film|res,write,create|h|H|p|Research a historical topic and present it as a paper, exhibit, documentary, website, or performance.|Use primary sources early; judges look for them.",
  "The Concord Review|comp|hum|hist,wri|write,res|h,e|H|o|Quarterly journal publishing high school history research papers.|Expect a long, heavily sourced paper.",
  "John Locke Institute Essay Competition|comp|hum|phil,law,bus,hist,psy|write,res|e,h,ec|M|o|Essay prompts in philosophy, politics, economics, history, psychology, and more.|Answer the question asked; judges penalize drifting.",
  "National History Bee and Bowl|comp|hum|hist|comp,team|h|L|p|Buzzer-based history quiz competitions.|Good fit if you already love history trivia.",
  "Quiz Bowl (NAQT)|club|hum|und,hist,wri|comp,team|h,e,b|M|p|Buzzer quiz competition across all academic subjects.|Specialize in a subject your team lacks.",
  "Academic Decathlon (USAD)|comp|hum|und|comp,team,speak|e,h,ec,a|H|p|Ten-event academic competition built around a yearly theme.|Teams mix A, B, and C students, so everyone counts.",
  "North American Computational Linguistics Open (NACLO)|comp|hum|lang,cs|math,res,comp|l,c|L|p|Solve language puzzles with no prior linguistics knowledge.|Past puzzles are free online and fun.",
  "National Latin Exam|comp|hum|lang,hist|comp|l|L|p|Exam for Latin students at every level.|Ask your Latin teacher to register your class.",
  "National Spanish Examinations|comp|hum|lang,ir|comp|l|L|o|Online Spanish exams for students of all levels.|Practice exams are available from the organizer.",
  "Le Grand Concours (National French Contest)|comp|hum|lang,ir|comp|l|L|o|National French exam for students across levels.|Your French teacher registers the school.",
  "National German Exam (AATG)|comp|hum|lang,ir|comp|l|L|o|National German exam that can lead to study trips.|Ask about the AATG study trip award.",
  "State Seal of Biliteracy|course|hum|lang,ir,edu|write,speak|l|M|p|Earn a seal on your diploma for proficiency in two languages.|Heritage speakers often qualify; ask your counselor.",
  "Junior Classical League (JCL)|club|hum|lang,hist|comp,create|l,h|M|p|Latin and classics club with conventions and academic contests.|State conventions mix tests, art, and athletics.",
  // Writing and media
  "Scholastic Art and Writing Awards|comp|media|wri,art,film|write,create|e,a|M|o|The longest-running recognition program for creative teens in writing and art.|Regional deadlines fall in December and January.",
  "YoungArts|comp|arts|art,mus,wri,film|create|a,mu,e,t|M|o|National arts competition for artists ages 15 to 18 in many disciplines.|Submit your strongest, most personal work.",
  "New York Times Learning Network Contests|comp|media|wri,jour|write,create|e|L|o|Free writing contests for teens, from personal essays to reviews.|Each contest has its own short window; check the calendar.",
  "Bennington Young Writers Awards|comp|media|wri|write,create|e|L|o|Writing awards in poetry, fiction, and nonfiction.|One polished piece beats several rough ones.",
  "Kenyon Review Young Writers Workshop|summer|media|wri|write,create|e|H|b|Selective summer creative writing workshop.|Send a writing sample that shows your own voice.",
  "Iowa Young Writers' Studio|summer|media|wri|write,create|e|H|b|Summer creative writing program from the University of Iowa.|Online and residential options exist.",
  "Adroit Journal Summer Mentorship|summer|media|wri|write,create|e|M|o|Free online mentorship pairing students with writers.|Apply with your best poems or prose.",
  "Polyphony Lit|vol|media|wri,edu|write,help|e|L|o|International literary magazine run by students; volunteer as an editor.|Editing work sharpens your own writing.",
  "Teen Ink|proj|media|wri,jour|write|e|L|o|Teen-written magazine and website accepting essays, fiction, and poetry.|Publication gives you a link to share.",
  "Poetry Out Loud|comp|media|wri,mus|speak,create|e,t|L|p|National poetry recitation contest.|Pick poems with different tones for each round.",
  "School Newspaper or Yearbook|club|media|jour,wri|write,team,org|e|M|p|Report, edit, and publish for your school.|Aim for an editor role by senior year.",
  "Literary Magazine|club|media|wri,art|write,create|e,a|L|p|Publish creative work from students at your school.|Run an open mic to grow submissions.",
  "Princeton Summer Journalism Program|summer|media|jour,wri|write,res|e|M|b|Free journalism program for high-achieving low-income students.|Apply as a junior.",
  "C-SPAN StudentCam|comp|media|film,jour,law|create,res|g,e|M|o|Make a short documentary on a national policy theme.|Interviews with people on different sides score well.",
  "All American High School Film Festival|comp|arts|film|create,team|a,t|M|p|Film festival and competition for high school filmmakers.|Short films under 10 minutes fit more categories.",
  "NFFTY Film Festival|comp|arts|film|create|a|M|p|Festival for filmmakers 24 and under.|Submit a finished short with clean sound.",
  "Podcast or YouTube Channel|proj|media|jour,mus,bus,film|create,speak,org|e|M|o|Create media on a topic you care about.|Pick a niche tied to your major.",
  // Arts
  "Art Portfolio and Exhibitions|proj|arts|art,arch|create,build|a|H|p|Build a portfolio and show work in galleries and contests.|Art schools review portfolios, so start early.",
  "Congressional Art Competition|comp|arts|art|create|a|L|p|Each House district picks one student artwork to hang in the Capitol for a year.|Check your representative's office for the spring deadline.",
  "International Thespian Society|club|arts|mus,film,wri|create,team,speak|t|H|p|Theater honor society with festivals and individual events.|Tech categories exist for designers and stage managers.",
  "Theater Production|club|arts|mus,wri,film|create,team,speak|t|H|p|Act, direct, or run tech crew for shows.|Tech crew is great for engineers too.",
  "Band, Orchestra, or Choir|club|arts|mus|create,team|mu|H|p|Perform in school or regional ensembles.|All-State auditions add a strong distinction.",
  "All-State Music Ensembles|comp|arts|mus|create,comp|mu|H|p|Audition for your state's top honor band, orchestra, or choir.|Audition excerpts are released months ahead.",
  "MTNA Performance Competitions|comp|arts|mus|create,comp|mu|H|p|Music Teachers National Association competitions for piano, strings, voice, and more.|Entry is usually through an MTNA member teacher.",
  "Interlochen Arts Camp|summer|arts|mus,art,wri,film|create|mu,a,t|H|p|Residential summer arts camp in Michigan.|Scholarships are available for many programs.",
  "Dance Team or Company|club|arts|mus,kin|create,team|t,he|H|p|Train and perform with a school or studio dance company.|Choreographing a piece shows creative leadership.",
  // Environment and agriculture
  "Envirothon|comp|env|env,bio,ag|res,team,comp|es,b|M|p|Team competition on soils, forestry, aquatics, and wildlife.|Great fit if you love being outdoors.",
  "Environmental Club|club|env|env,bio,law|lead,org,build|es|M|p|Lead cleanups, gardens, or sustainability campaigns.|Measure impact, like pounds of trash or trees planted.",
  "Bow Seat Ocean Awareness Contest|comp|env|env,art,wri|create,write|es,a,e|M|o|Art, writing, film, and music contest about ocean and climate issues.|Any creative medium is accepted.",
  "President's Environmental Youth Award|comp|env|env|lead,org|es|H|p|EPA award for K-12 environmental projects.|Document your project's measurable results.",
  "Student Conservation Association Crew|summer|env|env,ag|build,team|es|H|p|Summer conservation crews restore trails and habitats.|Many crews are paid.",
  "GLOBE Program|res|env|env,bio|res|es,b|L|b|NASA-supported citizen science collecting environmental data.|Pick one protocol and collect data consistently.",
  "eBird Citizen Science|proj|env|env,bio|res|es,b|L|p|Log bird sightings that scientists use for research.|Regular checklists from one spot are most useful.",
  "iNaturalist Projects|proj|env|env,bio|res|es,b|L|p|Photograph and identify species for a global biodiversity database.|Start or join a project for your town.",
  "Zooniverse Research Projects|res|stem|env,bio,hist,chem|res|es,b,h,p|L|o|Classify data for real research projects online.|Pick one project and go deep.",
  "National FFA Organization|club|env|ag,env,bus|lead,comp,build|es,b,bu|H|p|Agricultural education organization with competitive events and projects.|Supervised agricultural experience projects are a core part.",
  "4-H|club|env|ag,env,edu|lead,build,help|es,b|M|p|Youth development program with projects in science, agriculture, and leadership.|Pick a project area and show at a county fair.",
  // Service and leadership
  "Key Club|club|svc|und,edu,law|help,org,team|he|L|p|Student-led service club sponsored by Kiwanis.|Run for an officer position.",
  "Interact Club|club|svc|und,ir|help,lead|g|L|p|Rotary-sponsored service club for ages 12 to 18.|Interact clubs often run one international project a year.",
  "National Honor Society|club|svc|und|lead,help|he|L|p|Honor society with service and leadership requirements.|Track your service hours carefully.",
  "Habitat for Humanity Youth Program|vol|svc|arch,eng,und|build,help,team|p|M|p|Help build and repair homes with local affiliates.|Age rules differ by affiliate and job site.",
  "Tutoring Younger Students|vol|svc|edu,math,wri,und|help,lead,speak|m,e|L|p|Tutor peers or run a free class in your community.|Starting a program beats only joining one.",
  "Camp Counselor|work|svc|edu,psy|lead,help,team|ps|M|p|Lead groups of kids at a summer camp.|Summer-only, so it fits busy school years.",
  "Scouting America (Eagle Scout)|lead|svc|und,eng,law|lead,org,help|he|H|p|Advance through scouting ranks with a final service project.|Your Eagle project is your best story; make it measurable.",
  "Girl Scouts Gold Award|lead|svc|und,edu,env|lead,org,help|he|H|p|Girl Scouts' highest award for a sustainable community project.|Pick a root cause, not just a one-time event.",
  "Civil Air Patrol Cadet Program|club|svc|eng,law|lead,team|p|M|p|Air Force auxiliary cadet program with aerospace education and leadership.|Cadets can earn orientation flights.",
  "JROTC|club|svc|law,eng,kin|lead,team,org|g,he|H|p|Leadership and citizenship program offered in many high schools.|Leadership ranks give clear progression.",
  "Peer Mentor for New Students|lead|svc|edu,psy|help,lead|ps|L|p|Help incoming freshmen or transfer students get settled.|Ask your counselor whether a program exists.",
  // Athletics
  "Varsity Sports|club|ath|und,kin,edu|team,comp,lead|he|H|p|Train and compete on a school team.|Captain roles show leadership.",
];
