import type { Row } from "../taxonomy";

/* Real scholarships and awards. Amounts and rules change every year, so descriptions stay general
   and the site tells students to confirm details with the sponsor. */
export const SCHOLARSHIPS: Row[] = [
  // National merit and leadership
  "Coca-Cola Scholars Program|schol|svc|und|lead,help,org|he|L|o|One of the largest achievement-based scholarships for high school seniors who show leadership and service.|The application opens in late summer and closes in the fall of senior year.",
  "QuestBridge National College Match|schol|svc|und|write,res|e|M|o|Matches high-achieving, low-income seniors with full four-year scholarships at partner colleges.|Juniors can start with the QuestBridge College Prep Scholars program.",
  "The Gates Scholarship|schol|svc|und|lead,help|he|M|o|Full cost-of-attendance scholarship for outstanding minority students from low-income households.|Requires Pell Grant eligibility; apply in early fall of senior year.",
  "Jack Kent Cooke College Scholarship|schol|svc|und|res,write|e|M|o|Large scholarship for high-achieving high school seniors with financial need.|Strong grades plus clear financial need are the core criteria.",
  "Dell Scholars Program|schol|svc|und|org,help|he|M|o|Scholarship plus ongoing support for students who've overcome obstacles and are Pell-eligible.|It values grit and determination over perfect grades.",
  "Horatio Alger National Scholarship|schol|svc|und|help,write|e|L|o|Need-based scholarship for students who have faced and overcome great obstacles.|State-level Horatio Alger scholarships open at the same time.",
  "National Merit Scholarship Program|schol|stem|und|math,write|m,e|L|p|Recognition and scholarships based on junior-year PSAT/NMSQT scores.|Take the PSAT in October of junior year; that's the qualifying test.",
  "Elks Most Valuable Student Scholarship|schol|svc|und|lead,help|he|L|o|Elks National Foundation scholarship judged on scholarship, leadership, and financial need.|Applications open in the fall for seniors.",
  "Burger King Scholars Program|schol|svc|und|help,org|he|L|o|Scholarships for students with work experience, community service, and financial need.|Part-time work counts in your favor.",
  "Equitable Excellence Scholarship|schol|svc|und|lead,help|he|L|o|Scholarship for students who show ambition and self-drive in their community.|Write about one specific impact you made.",
  "Comcast Leaders and Achievers Scholarship|schol|svc|und|lead,help|he|L|o|Scholarship for seniors in Comcast service areas who show leadership and service.|Nomination usually comes through your high school.",
  "Taco Bell Live Mas Scholarship|schol|arts|und,film,art|create|a|L|o|Passion-based scholarship that asks for a short video instead of grades or essays.|Show the passion, not your resume.",
  "Cameron Impact Scholarship|schol|svc|und|lead,help|he|M|o|Four-year merit scholarship for students with strong leadership and community impact.|The application opens in the spring of junior year.",
  "Prudential Emerging Visionaries|schol|biz|bus,und|create,lead|bu,ec|M|o|Awards and mentoring for young people solving financial or societal challenges.|Ages 14 to 18; describe a project that already exists.",
  "Ron Brown Scholar Program|schol|civ|und,law|lead,help|g|M|o|Scholarship and network for academically talented Black high school seniors committed to service.|Essays carry a lot of weight; start early.",
  "Jackie Robinson Foundation Scholarship|schol|svc|und|lead,help|he|M|o|Scholarship and mentoring for students of color with leadership potential and financial need.|Requires a demonstrated record of community service.",
  "Hispanic Scholarship Fund|schol|svc|und|lead|he|L|o|Scholarships for students of Hispanic heritage pursuing college.|Requires a minimum GPA and FAFSA completion.",
  "UNCF Scholarships|schol|svc|und|lead|he|L|o|Hundreds of scholarship programs, many for students attending HBCUs.|Create one UNCF profile to be matched to multiple awards.",
  "Thurgood Marshall College Fund Scholarships|schol|svc|und|lead|he|L|o|Scholarships for students attending public HBCUs.|Check which member schools you're applying to.",
  "APIA Scholars|schol|svc|und|lead,help|he|L|o|Scholarships for Asian American, Native Hawaiian, and Pacific Islander students with financial need.|One application covers many awards.",
  "Posse Foundation Scholarship|schol|svc|und|lead,team|he|M|p|Full-tuition leadership scholarships for teams of students sent to partner colleges together.|You must be nominated by your school or a community organization.",
  "Hispanic Heritage Youth Awards|schol|svc|und|lead,help|he|L|o|Recognition and grants for Latino high school seniors in many fields.|Pick the category closest to your intended major.",
  "National Honor Society Scholarship|schol|svc|und|lead,help|he|L|o|Scholarships for NHS members nominated by their chapter.|Ask your chapter adviser about the nomination timeline.",
  "AISES Scholarships|schol|stem|eng,cs,bio,env|res|m,b|L|o|Scholarships for Indigenous students in STEM from the American Indian Science and Engineering Society.|Membership is free for students.",
  "Society of Women Engineers Scholarships|schol|stem|eng,cs|build,math|p,m|L|o|Scholarships for women entering engineering and computer science programs.|Incoming first-year students can apply.",
  "SHPE Scholarships|schol|stem|eng,cs|build,math|p,m|L|o|Scholarships from the Society of Hispanic Professional Engineers.|High school seniors are eligible for some awards.",
  "NSBE Scholarships|schol|stem|eng,cs|build,math|p,m|L|o|Scholarships from the National Society of Black Engineers.|NSBE Jr. chapters exist in many high schools.",
  // Essay and speech contests with prizes
  "Ayn Rand Institute Essay Contests|schol|hum|phil,wri|write|e|L|o|Essay contests on Ayn Rand's novels with cash prizes.|Read the specific novel for your grade level.",
  "VFW Voice of Democracy|schol|civ|law,wri|write,speak|g,e|L|p|Audio essay competition on a patriotic theme with national scholarships.|Entries go through your local VFW post in the fall.",
  "American Legion Oratorical Contest|schol|civ|law|speak|g|M|p|Constitutional speech contest with scholarship prizes.|Memorize a prepared oration and practice assigned topics.",
  "Optimist International Oratorical Contest|schol|civ|und,law|speak|e|L|p|Speech contest for young people with scholarships at the district level.|Contact a local Optimist Club to enter.",
  // University named scholarships
  "Morehead-Cain Scholarship (UNC)|schol|svc|und|lead,help|he|M|o|Full four-year merit scholarship at UNC Chapel Hill.|Applying to UNC is the first step; the scholarship has its own application.",
  "Jefferson Scholars Program (UVA)|schol|svc|und|lead,res|he|M|p|Full merit scholarship at the University of Virginia.|Most candidates are nominated by their high school.",
  "Robertson Scholars Leadership Program|schol|svc|und|lead|he|M|o|Scholarship spanning Duke and UNC Chapel Hill.|Apply alongside your Duke or UNC application.",
  "Park Scholarships (NC State)|schol|svc|und|lead,help|he|M|o|Full four-year scholarship at NC State.|Apply to NC State by the early action deadline.",
  "Stamps Scholars Program|schol|svc|und|lead,res|he|L|o|Merit scholarships offered through dozens of partner universities.|Each partner school runs its own selection.",
  "Presidential Scholars and Honors College Scholarships|schol|svc|und|lead|he|L|o|Many public universities give automatic or competitive merit aid to strong applicants.|Check each school's merit scholarship deadline; it's often earlier than admissions.",
  // State aid
  "Florida Bright Futures Scholarship|schol|svc|und|org|he|L|o|State merit scholarship for Florida students attending Florida colleges.|Track required GPA, test scores, and service hours.",
  "Georgia HOPE Scholarship|schol|svc|und|org|he|L|o|State merit scholarship for Georgia residents at Georgia colleges.|Your HOPE GPA is calculated by the state; check it each year.",
  "Cal Grant|schol|svc|und|org|he|L|o|California state financial aid for students attending California colleges.|File the FAFSA or CA Dream Act application by the March deadline.",
  "Tennessee HOPE Scholarship|schol|svc|und|org|he|L|o|Lottery-funded scholarship for Tennessee students.|ACT/SAT or GPA requirements apply.",
  "Louisiana TOPS|schol|svc|und|org|he|L|o|State scholarship for Louisiana students attending Louisiana colleges.|Core curriculum requirements start in 9th grade.",
  "South Carolina LIFE Scholarship|schol|svc|und|org|he|L|o|State merit scholarship for South Carolina residents.|Eligibility is checked by your college.",
  "Kentucky KEES|schol|svc|und|org|he|L|o|Kentucky Educational Excellence Scholarship earned each year of high school.|Every year's GPA adds to your award.",
  "West Virginia PROMISE Scholarship|schol|svc|und|org|he|L|o|Merit scholarship for West Virginia students.|Apply through the state's College Foundation of West Virginia site.",
  "New Mexico Lottery Scholarship|schol|svc|und|org|he|L|o|Tuition support for New Mexico residents at in-state colleges.|Enroll full-time right after high school to stay eligible.",
  "Federal Pell Grant (via FAFSA)|schol|svc|und|org|he|L|o|Federal grant for students with financial need; you don't pay it back.|File the FAFSA as soon as it opens senior year.",
  "CSS Profile Aid|schol|svc|und|org|he|L|o|Many private colleges use the CSS Profile to award their own grants.|Check which of your colleges require it and their deadlines.",
  // Local
  "Local Community Foundation Scholarships|schol|svc|und|help|he|L|o|Most counties have a community foundation that offers many small local scholarships.|Local awards get far fewer applicants than national ones.",
  "Rotary Club Scholarships|schol|svc|und|lead,help|he|L|p|Many local Rotary clubs give scholarships to seniors in their area.|Call your local club in the fall.",
  "Lions Club Scholarships|schol|svc|und|help|he|L|p|Local Lions Clubs often fund scholarships for nearby students.|Ask your counselor which service clubs give local awards.",
  "Credit Union Scholarships|schol|biz|und,bus|org|ec|L|o|Many credit unions offer scholarships to members and their families.|Check your family's credit union website in winter.",
  "Parent Employer Scholarships|schol|biz|und|org|he|L|o|Many employers offer scholarships to employees' children.|Ask your parents to check their HR or benefits site.",
  "School Counseling Office Scholarship List|schol|svc|und|org|he|L|p|Your school usually keeps a list of local scholarships with smaller applicant pools.|Check it every month of senior year.",
];
